import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css"; // Note the @ symbol
import Navbar from "../components/Navbar";
import Footer from "../components/Footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-ingwe-dark text-white selection:bg-ingwe-blue selection:text-white`}>
        <Navbar />
        <main className="pt-24 min-h-screen"> {/* pt-24 ensures content isn't hidden under the fixed nav */}
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
